export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_MARVEL_CHARACTER = "FETCH_MARVEL_CHARACTER";
export const FETCH_CHARACTER = "FETCH_CHARACTER";
export const EDIT_CHARACTER = "EDIT_CHARACTER";
